"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const router = (0, express_1.Router)();
const userController_1 = require("../controllers/userController");
const message_1 = require("../services/message");
const authToken_1 = __importDefault(require("../middleware/authToken"));
const multer_1 = __importDefault(require("multer"));
const upload = (0, multer_1.default)();
router.post("/register", userController_1.register);
router.post("/login", userController_1.login);
router.get("/logoutUser", authToken_1.default, userController_1.logoutUser);
router.get("/getCurrentUserDetails", authToken_1.default, userController_1.currentUser);
router.post("/addContact", authToken_1.default, userController_1.addContact);
router.get("/getAllContacts", authToken_1.default, userController_1.getAllContacts);
router.post("/addGroup", authToken_1.default, userController_1.addGroup);
router.get("/getAllGroups", authToken_1.default, userController_1.getAllGroups);
router.get("/getAllMembers/:groupId", authToken_1.default, userController_1.getAllGroupMembers);
router.get("/getAllAdmins/:groupId", authToken_1.default, userController_1.getAllAdmins);
router.get("/leaveGroup/:groupId", authToken_1.default, userController_1.leaveGroup);
router.post("/sendMessage", authToken_1.default, message_1.sendMessage);
router.post("/sendMediaMessage", upload.single('file'), authToken_1.default, message_1.sendMediaMessage);
router.get("/getAllPrivateMessages", authToken_1.default, message_1.getAllPrivateMessages);
router.post("/getAllGroupMessages", authToken_1.default, message_1.getAllGroupMessages);
router.post("/adminOps", authToken_1.default, userController_1.adminOperations);
router.get('/getAllInvites', authToken_1.default, userController_1.getAllInvites);
router.post("/responseInvites", authToken_1.default, userController_1.responseInvites);
exports.default = router;
